language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-23
    - extra-android-m2repository

before_install:
  - script/start_emulator.sh
